### ISSUE TITLE
点击按钮没反应

### ISSUE THREAD

**Issue by MInggongK** [XiLitter/Tp_Attack_GUI#4]
![fgdgdgd](https://github.com/user-attachments/assets/40b1c907-eada-47d9-938e-3610efeb8579)
![fgddgdg](https://github.com/user-attachments/assets/87e82c69-f168-41d6-8ce4-93278e9fcc83)

**Comment by XiLitter** [comment]
你的超时设置选项没有写

**Comment by MInggongK** [comment]
/
![fsdff](https://github.com/user-attachments/assets/e680b03b-ca53-4fe0-97d9-d86b168c7028)
有bug

**Comment by XiLitter** [comment]
确实有bug，验证返回包内容不规范，多谢
